apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: mypod
    tier: frontend
spec:
  replicas: 4
  template:
    metadata:
      name: myapp-pod
      labels:
        app: mypod
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      app: myapp
